name: CI Pipleline For Issuer

on: 
  push:
    branches:    
      - master 

jobs:
   build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with:
        node-version: '14.4.0'
    
    - name: npm install and build
      run: |
        npm install
        npm run build --if-present
    
      env:
        CI: false
        GITHUB_SHA: ${{ github.sha }}
    
    - name: Add remote origin
      run: |
        git remote add heroku_node https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git fetch --unshallow
        git push heroku_node master
